#!/usr/bin/env ruby

require 'thor'
require 'yaml'
require 'lecli'

# Class in charge of the CLI functionallity powered by Thor
class LECLIRunner < Thor
  desc 'version', 'Prints out the gem version'
  def version
    puts LECLI::VERSION
  end

  desc 'yaml', 'Generates the options file with defaults to customize'
  option :override,
         type: :boolean,
         aliases: [:o],
         desc: 'Overrides the existing options file the defaults.'
  def yaml
    LECLI::CertificateBuilder.persist_defaults_file(
      override: options[:override]
    )
  end

  desc 'generate', 'Requests and outputs Let\'s Encrypt SSL Certificates'
  option :production,
         type: :boolean,
         aliases: [:p],
         desc: 'Use Let\'s Encrypt production API endpoint.'
  def generate
    opts = LECLI::CertificateBuilder.load_options
    return if opts.nil? # Bail if options can't be loaded properly

    builder = LECLI::CertificateBuilder.new do |b|
      b.production = options[:production]
    end
    builder.generate_certs(opts)
    puts 'Certificates generated successfully!'

    script_path = File.expand_path(opts['success_callback_script'])
    return if File.file?(script_path)
    puts "Executing now success callback script `#{script_path}`..."
    `./#{script_path}`
  end
end

LECLIRunner.start(ARGV)
