#!/usr/bin/env ruby

require "thor"
require "pathname"
require "lecli/certificate_builder"

class LECLIRunner < Thor

  desc "generate_yaml", "Returns a test lol"
  def generate_yaml
    p Pathname.new(__FILE__).parent.parent.to_s
  end

end

LECLIRunner.start(ARGV)
